"""
TheHive API client for automated case creation.
"""

import os
import logging
import httpx

logger = logging.getLogger(__name__)

SEVERITY_MAP = {"LOW": 1, "MEDIUM": 2, "HIGH": 3, "CRITICAL": 4}


class TheHiveClient:
    def __init__(self):
        self.base_url = os.getenv("THEHIVE_URL", "http://thehive:9000")
        self.api_key = os.getenv("THEHIVE_API_KEY", "")
        self.headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

    async def create_case(self, alert: dict, triage: dict) -> dict | None:
        title = f"[AI-SOC] {alert.get('rule_description', 'Security Alert')}"
        severity = SEVERITY_MAP.get(triage.get("severity_normalized", "MEDIUM"), 2)

        description = self._build_description(alert, triage)

        payload = {
            "title": title,
            "description": description,
            "severity": severity,
            "tags": [
                f"source:{alert.get('source', 'unknown')}",
                f"verdict:{triage.get('verdict')}",
                triage.get("mitre_technique", "unknown").split(" - ")[0],
            ],
            "tlp": 2,
            "status": "New",
            "customFields": {
                "ai-verdict": {"string": triage.get("verdict")},
                "ai-confidence": {"float": triage.get("confidence")},
                "mitre-tactic": {"string": triage.get("mitre_tactic", "")},
                "mitre-technique": {"string": triage.get("mitre_technique", "")},
                "source-ip": {"string": alert.get("source_ip", "")},
            },
        }

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(
                    f"{self.base_url}/api/case",
                    headers=self.headers,
                    json=payload,
                )
                resp.raise_for_status()
                case = resp.json()
                logger.info(f"TheHive case created: {case.get('_id')} for alert {alert.get('alert_id')}")
                return case
        except Exception as e:
            logger.error(f"TheHive case creation failed: {e}")
            return None

    def _build_description(self, alert: dict, triage: dict) -> str:
        return f"""## AI-Generated Incident Summary

{triage.get('summary', 'No summary available.')}

---

## Alert Details

| Field | Value |
|-------|-------|
| Alert ID | `{alert.get('alert_id')}` |
| Source | {alert.get('source')} |
| Rule | {alert.get('rule_id')} — {alert.get('rule_description')} |
| Source IP | `{alert.get('source_ip', 'N/A')}` |
| Destination IP | `{alert.get('dest_ip', 'N/A')}` |
| Hostname | `{alert.get('hostname', 'N/A')}` |
| Timestamp | {alert.get('timestamp')} |

---

## AI Triage Output

- **Verdict**: {triage.get('verdict')}
- **Confidence**: {triage.get('confidence', 0):.0%}
- **MITRE Tactic**: {triage.get('mitre_tactic')}
- **MITRE Technique**: {triage.get('mitre_technique')}

---

## Recommended Response

{triage.get('response_recommendation', 'No recommendation.')}

---

## Response Playbook

{chr(10).join(f"{i+1}. {step}" for i, step in enumerate(triage.get('playbook_steps', [])))}

---

## Raw Log

```
{alert.get('raw_log', 'N/A')}
```

---
*Generated by AI SOC Engine — {triage.get('ai_model')} | Processing time: {triage.get('processing_time_ms')}ms*
"""
